import type { Campaign } from './types'

export const STORY_CAMPAIGN: Campaign = {
  id: 'story',
  title: 'Story Mode',
  chapters: [
    {
      id: 'first-contact',
      title: 'First Contact',
      setting: 'A quiet evening on the beginner band',
      blurb: 'Answer a friendly CQ and finish a short first QSO.',
      characters: [
        {
          id: 'maya',
          name: 'Maya',
          callsign: 'W1AW',
          avatar: 'M',
          locale: 'US',
        },
      ],
      lines: [
        {
          id: 'intro',
          speaker: 'maya',
          text: 'FIRST CONTACT',
          subtitle: 'Maya is calling CQ. Listen first, then copy what you hear.',
          mode: 'narration',
        },
        {
          id: 'cq',
          speaker: 'maya',
          text: 'CQ CQ DE W1AW',
          subtitle: 'Calling any station, this is W1AW.',
          timing: { charWpm: 16, effectiveWpm: 8 },
          mode: 'copy',
          passAccuracy: 0.8,
        },
        {
          id: 'answer-cq',
          speaker: 'you',
          text: 'W1AW DE G4ABC K',
          subtitle: 'You answer and invite Maya to continue.',
          mode: 'send',
        },
        {
          id: 'rst',
          speaker: 'maya',
          text: 'G4ABC DE W1AW RST 599',
          subtitle: 'Maya sends your signal report.',
          timing: { charWpm: 16, effectiveWpm: 8 },
          mode: 'copy',
          passAccuracy: 0.8,
        },
        {
          id: 'send-rst',
          speaker: 'you',
          text: 'W1AW DE G4ABC RST 579',
          subtitle: 'You send Maya a signal report back.',
          mode: 'send',
        },
        {
          id: 'name',
          speaker: 'maya',
          text: 'NAME MAYA',
          subtitle: 'Her name is Maya.',
          timing: { charWpm: 17, effectiveWpm: 9 },
          mode: 'copy',
          passAccuracy: 0.85,
        },
        {
          id: 'your-name',
          speaker: 'you',
          text: 'NAME BEN',
          subtitle: 'You send your name.',
          mode: 'send',
        },
        {
          id: 'qth',
          speaker: 'maya',
          text: 'QTH BOSTON',
          subtitle: 'Maya sends her location.',
          timing: { charWpm: 17, effectiveWpm: 9 },
          mode: 'copy',
          passAccuracy: 0.85,
        },
        {
          id: 'thanks',
          speaker: 'maya',
          text: 'TU 73',
          subtitle: 'Thanks, best regards.',
          timing: { charWpm: 18, effectiveWpm: 10 },
          mode: 'copy',
          passAccuracy: 0.9,
        },
        {
          id: 'close',
          speaker: 'you',
          text: '73 SK',
          subtitle: 'You close the contact.',
          mode: 'send',
        },
      ],
    },
  ],
}
