import type { Campaign } from './types'

export const STORY_CAMPAIGN: Campaign = {
  id: 'story',
  title: 'Story Mode',
  chapters: [
    {
      id: 'first-contact',
      title: 'First Contact',
      setting: 'A quiet evening on the beginner band',
      blurb: 'Answer a friendly CQ and finish a short first QSO.',
      characters: [
        {
          id: 'maya',
          name: 'Maya',
          callsign: 'W1AW',
          avatar: 'M',
          locale: 'US',
        },
      ],
      lines: [
        {
          id: 'intro',
          speaker: 'maya',
          text: 'FIRST CONTACT',
          subtitle: 'Maya is calling CQ. Listen first, then copy what you hear.',
          mode: 'narration',
        },
        {
          id: 'cq',
          speaker: 'maya',
          text: 'CQ CQ DE W1AW',
          subtitle: 'Calling any station, this is W1AW.',
          timing: { charWpm: 16, effectiveWpm: 8 },
          mode: 'copy',
          passAccuracy: 0.8,
        },
        {
          id: 'answer-cq',
          speaker: 'you',
          text: 'W1AW DE G4ABC K',
          subtitle: 'You answer and invite Maya to continue.',
          mode: 'send',
        },
        {
          id: 'rst',
          speaker: 'maya',
          text: 'G4ABC DE W1AW RST 599',
          subtitle: 'Maya sends your signal report.',
          timing: { charWpm: 16, effectiveWpm: 8 },
          mode: 'copy',
          passAccuracy: 0.8,
        },
        {
          id: 'send-rst',
          speaker: 'you',
          text: 'W1AW DE G4ABC RST 579',
          subtitle: 'You send Maya a signal report back.',
          mode: 'send',
        },
        {
          id: 'name',
          speaker: 'maya',
          text: 'NAME MAYA',
          subtitle: 'Her name is Maya.',
          timing: { charWpm: 17, effectiveWpm: 9 },
          mode: 'copy',
          passAccuracy: 0.85,
        },
        {
          id: 'your-name',
          speaker: 'you',
          text: 'NAME BEN',
          subtitle: 'You send your name.',
          mode: 'send',
        },
        {
          id: 'qth',
          speaker: 'maya',
          text: 'QTH BOSTON',
          subtitle: 'Maya sends her location.',
          timing: { charWpm: 17, effectiveWpm: 9 },
          mode: 'copy',
          passAccuracy: 0.85,
        },
        {
          id: 'thanks',
          speaker: 'maya',
          text: 'TU 73',
          subtitle: 'Thanks, best regards.',
          timing: { charWpm: 18, effectiveWpm: 10 },
          mode: 'copy',
          passAccuracy: 0.9,
        },
        {
          id: 'close',
          speaker: 'you',
          text: '73 SK',
          subtitle: 'You close the contact.',
          mode: 'send',
        },
      ],
    },
    {
      id: 'storm-watch',
      title: 'Storm Watch',
      setting: 'A coastal net as the weather turns',
      blurb: 'Copy a short weather relay and pass it back cleanly.',
      unlock: { previousChapterId: 'first-contact' },
      characters: [
        {
          id: 'nora',
          name: 'Nora',
          callsign: 'K2SEA',
          avatar: 'N',
          locale: 'US',
        },
      ],
      lines: [
        {
          id: 'intro',
          speaker: 'nora',
          text: 'STORM WATCH',
          subtitle: 'Nora is running a small coastal weather net.',
          mode: 'narration',
        },
        {
          id: 'net-cq',
          speaker: 'nora',
          text: 'CQ NET DE K2SEA',
          subtitle: 'K2SEA calls stations into the net.',
          timing: { charWpm: 17, effectiveWpm: 9 },
          mode: 'copy',
          passAccuracy: 0.8,
        },
        {
          id: 'answer-net',
          speaker: 'you',
          text: 'K2SEA DE G4ABC K',
          subtitle: 'You answer the net control station.',
          mode: 'send',
        },
        {
          id: 'weather',
          speaker: 'nora',
          text: 'WX RAIN WIND 20',
          subtitle: 'Weather: rain, wind at 20.',
          timing: { charWpm: 18, effectiveWpm: 10 },
          mode: 'copy',
          passAccuracy: 0.85,
        },
        {
          id: 'confirm-weather',
          speaker: 'you',
          text: 'QSL WX RAIN WIND 20',
          subtitle: 'You confirm the weather report.',
          mode: 'send',
        },
        {
          id: 'port',
          speaker: 'nora',
          text: 'QTH PORTSMOUTH',
          subtitle: 'Nora gives the station location.',
          timing: { charWpm: 18, effectiveWpm: 10 },
          mode: 'copy',
          passAccuracy: 0.85,
        },
        {
          id: 'relay',
          speaker: 'nora',
          text: 'NR 3 NEED RELAY',
          subtitle: 'Message number 3 needs a relay.',
          timing: { charWpm: 19, effectiveWpm: 11 },
          mode: 'copy',
          passAccuracy: 0.9,
        },
        {
          id: 'close',
          speaker: 'you',
          text: 'R R 73',
          subtitle: 'You acknowledge and close.',
          mode: 'send',
        },
      ],
    },
  ],
}
